config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'proyectos/index', to: 'proyectos#index'
get 'proyectos/new', to: 'proyectos#new', as: 'new_proyecto'
post 'proyectos', to: 'proyectos#create', as: 'proyectos'
get 'proyectos/dashboard', to: 'proyectos#dashboard'

root 'proyectos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
  validates :name , presence: {message: 'empty'}

  validates :begin_at , presence: {message: 'empty'}
  validates :end_at , presence: {message: 'empty'}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proyectos_controller.rb
class ProyectosController <ApplicationController

  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only:
  :dashboard



  def new
    @post=Proyecto.new
  end

  def create
    @post = Proyecto.new(proyecto_params)
      if  @post.save
       redirect_to root_path, notice: 'guardamos'
     else
       render new_proyecto_path, alert: ' no guardamos'
   end

  end

  def dashboard
    if params[:status].present?
@posts = Proyecto.where('status = ?', params[:status])
else
     @posts = Proyecto.all
  end
end

def index
end
  private
   def proyecto_params
     params.require(:proyecto).permit(:name, :descripcion, :begin_at, :end_at, :status)
   end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gpro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/proyectos/dashboard.html.erb
<h1 class="text-center m-4 text-dark"> Elige los proyectos</h1>
<nav class="navbar navbar-light bg-light justify-content-between">
<a class="navbar-brand">Elige el status</a>
<form class="form-inline">
<input class="form-control mr-sm-2" type="search" placeholder="Search"
aria-label="Search" name="status">
<button class="btn btn-outline-success my-2 my-sm-0"
type="submit">Search</button>
</form>
</nav>


 <%  @posts.each_slice(2) do |post2| %>

  <div class="card-deck m-4">
    <%  post2.each do |post| %>

  <div class="card p-4">

    <div class="card-body">

      <h5 class="card-title">Name</h5>
      <p class="card-text"><%= post.name %></p>
      <h5 class="card-title">Description</h5>
      <p class="card-text"><%= post.descripcion %></p>
      <h5 class="card-title">Begin_at</h5>
      <p class="card-text"><%= post.begin_at %></p>
      <h5 class="card-title">End_at</h5>
      <p class="card-text"><%= post.end_at %></p>
      <h5 class="card-title">Status</h5>
      <p class="card-text"><%= post.status %></p>

  </div>
  </div>
  <% end %>
  </div>
   <% end %>


<h3><%= link_to "Inicio", root_path %></h3>
<h3> <%= link_to "Formulario", new_proyecto_path %></h3>

app/views/proyectos/index.html.erb
<h1> Llena el formulario y ve tus proyectos</h1>

<h3><%= link_to "New", new_proyecto_path %></h3>
<h3><%= link_to "Dashboard", proyectos_dashboard_path %></h3>

app/views/proyectos/new.html.erb
<h1 class="text-center m-4 text-dark">Nuevo Proyecto</h1>

<div class="text-center m-4 " id="create_posts">


<div>
<%= form_with(model: @post, local: true) do |f| %>
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group pb-2">
<%= f.label :name %>
<%= f.text_field :name %>
</div>
   <div class="form-group pb-2">
<%= f.label :descripcion %>
<%= f.text_area :descripcion %>
</div>
   <div class="form-group pb-2">
<%= f.label :begin_at %>
<%= f.date_field :begin_at %>
</div>
   <div class="form-group pb-2">
<%= f.label :end_at %>
<%= f.date_field:end_at %>
</div>
   <div class="form-group pb-2">
<%= f.label :status %>
<%= f.select :status, options_for_select(['propuesta','en progreso', 'terminado'], 'propuesta')%>
</div>
<%= f.submit 'Guardar' %>

<% end %>
</div>
</div>
<h3><%= link_to "Inicio", root_path %></h3>
<h3><%= link_to "Dashboard", proyectos_dashboard_path %></h3>